# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7954a60f925cc89380b6f0862dd5de38b4b6699d90aa06081a03d6d05dc88933cd3cd3792bf306c05948581b115c8a87741aafe5acfe0925bfafc434c76451

test:
  secret_key_base: 0b6d88d71963fa03b71672184ae82762e67ac37682470e0733295f68ae4fab6ea16c863549f12e5ef1ba334daa27aad5a256b86e5f5e827b8ae5250c324f7583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
